"""Update indicator tables

Revision ID: 3c5f8a93321c
Revises: b617b82367b0
Create Date: 2024-06-20 17:38:03.796479

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3c5f8a93321c'
down_revision = 'b617b82367b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('unit_name', sa.String(), nullable=True))
    op.drop_index('ix_units_name', table_name='units')
    op.create_index(op.f('ix_units_unit_name'), 'units', ['unit_name'], unique=True)
    op.drop_column('units', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_units_unit_name'), table_name='units')
    op.create_index('ix_units_name', 'units', ['name'], unique=True)
    op.drop_column('units', 'unit_name')
    # ### end Alembic commands ###