"""empty message

Revision ID: 4bf042c7e3d7
Revises: 3c5f8a93321c
Create Date: 2024-07-18 10:55:48.373182

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4bf042c7e3d7'
down_revision = '3c5f8a93321c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detailed_indicator_values', sa.Column('male', sa.Float(), nullable=True))
    op.add_column('detailed_indicator_values', sa.Column('female', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detailed_indicator_values', 'female')
    op.drop_column('detailed_indicator_values', 'male')
    # ### end Alembic commands ###
