"""Indicator tables

Revision ID: b617b82367b0
Revises: 47570865a5ff
Create Date: 2024-06-20 15:56:05.982557

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b617b82367b0'
down_revision = '47570865a5ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'indicators',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('unit_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['unit_id'],
            ['units.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', 'unit_id', name='_name_unit_uc'),
    )
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    op.create_index(op.f('ix_indicators_name'), 'indicators', ['name'], unique=False)
    op.create_table(
        'aggregated_indicator_values',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('indicator_id', sa.Integer(), nullable=True),
        sa.Column('territory_id', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['indicator_id'],
            ['indicators.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_aggregated_indicator_values_id'), 'aggregated_indicator_values', ['id'], unique=False)
    op.create_index(
        op.f('ix_aggregated_indicator_values_indicator_id'),
        'aggregated_indicator_values',
        ['indicator_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_aggregated_indicator_values_territory_id'),
        'aggregated_indicator_values',
        ['territory_id'],
        unique=False,
    )
    op.create_index(op.f('ix_aggregated_indicator_values_year'), 'aggregated_indicator_values', ['year'], unique=False)
    op.create_table(
        'detailed_indicator_values',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('indicator_id', sa.Integer(), nullable=True),
        sa.Column('territory_id', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('age_start', sa.Integer(), nullable=False),
        sa.Column('age_end', sa.Integer(), nullable=False),
        sa.Column('gender', sa.String(), nullable=True),
        sa.Column('source', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['indicator_id'],
            ['indicators.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_detailed_indicator_values_id'), 'detailed_indicator_values', ['id'], unique=False)
    op.create_index(
        op.f('ix_detailed_indicator_values_indicator_id'), 'detailed_indicator_values', ['indicator_id'], unique=False
    )
    op.create_index(
        op.f('ix_detailed_indicator_values_territory_id'), 'detailed_indicator_values', ['territory_id'], unique=False
    )
    op.create_index(op.f('ix_detailed_indicator_values_year'), 'detailed_indicator_values', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detailed_indicator_values_year'), table_name='detailed_indicator_values')
    op.drop_index(op.f('ix_detailed_indicator_values_territory_id'), table_name='detailed_indicator_values')
    op.drop_index(op.f('ix_detailed_indicator_values_indicator_id'), table_name='detailed_indicator_values')
    op.drop_index(op.f('ix_detailed_indicator_values_id'), table_name='detailed_indicator_values')
    op.drop_table('detailed_indicator_values')
    op.drop_index(op.f('ix_aggregated_indicator_values_year'), table_name='aggregated_indicator_values')
    op.drop_index(op.f('ix_aggregated_indicator_values_territory_id'), table_name='aggregated_indicator_values')
    op.drop_index(op.f('ix_aggregated_indicator_values_indicator_id'), table_name='aggregated_indicator_values')
    op.drop_index(op.f('ix_aggregated_indicator_values_id'), table_name='aggregated_indicator_values')
    op.drop_table('aggregated_indicator_values')
    op.drop_index(op.f('ix_indicators_name'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
