"""empty message

Revision ID: bd4f6a7f8981
Revises: c2ce85abbe08
Create Date: 2024-07-26 10:33:48.630328

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'bd4f6a7f8981'
down_revision = 'c2ce85abbe08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detailed_indicator_values', 'age_start',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('detailed_indicator_values', 'age_end',
               existing_type=sa.INTEGER(),
               nullable=True)
    # op.create_check_constraint(
    #     "ck_male_female_not_null",
    #     "detailed_indicator_values",
    #     "COALESCE(male, female) is not null"
    # )
    op.create_check_constraint(
        "ck_age_start_age_end_not_null",
        "detailed_indicator_values",
        "COALESCE(age_start, age_end) is not null"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detailed_indicator_values', 'age_end',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('detailed_indicator_values', 'age_start',
               existing_type=sa.INTEGER(),
               nullable=False)
    # op.drop_constraint(
    #      "ck_male_female_not_null",
    #     "detailed_indicator_values"
    # )
    op.drop_constraint(
        "ck_age_start_age_end_not_null",
        "detailed_indicator_values"
    )
    # ### end Alembic commands ###