"""empty message

Revision ID: c2ce85abbe08
Revises: 4bf042c7e3d7
Create Date: 2024-07-18 10:59:54.454269

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c2ce85abbe08'
down_revision = '4bf042c7e3d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detailed_indicator_values', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detailed_indicator_values', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
